name: JJM Automation CI/CD

on:
  push:
    branches:
      - main # Trigger on main branch pushes
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      # 3. Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Run tests (if you have pytest/unittests)
      - name: Run tests
        run: |
          pytest || echo "⚠️ No tests configured yet"

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 5. Deploy with uvicorn/gunicorn (example using Docker)
      - name: Build & push Docker image
        run: |
          docker build -t jjm-automation .
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker tag jjm-automation ${{ secrets.DOCKER_USERNAME }}/jjm-automation:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/jjm-automation:latest

      # Optional: Deploy to server via SSH
      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/jjm-automation:latest
            docker stop jjm || true
            docker rm jjm || true
            docker run -d --name jjm -p 8000:8000 --env-file ./app/.env ${{ secrets.DOCKER_USERNAME }}/jjm-automation:latest
