name: JJM Automation CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t jjm-automation .

      - name: Push Docker image to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker tag jjm-automation ${{ secrets.DOCKER_USERNAME }}/jjm-automation:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/jjm-automation:latest

      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker stop jjm || true
            docker rm jjm || true
            docker pull ${{ secrets.DOCKER_USERNAME }}/jjm-automation:latest
            docker run -d --name jjm -p 9000:9000 --env-file ./app/.env.prod ${{ secrets.DOCKER_USERNAME }}/jjm-automation:latest
